image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: mix deps.get
    init: psql --command "CREATE USER postgres WITH SUPERUSER PASSWORD 'postgres';" && cd /workspace/gitpod-test/assets && npm install && node node_modules/webpack/bin/webpack.js --mode development && cd /workspace/gitpod-test && mix ecto.create
    command: mix ecto.migrate && mix run priv/repo/seeds.exs && iex -S mix phx.server

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
